routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(["domain" => config("app.guest_sub").".".config("app.root"), "as" => "guest."], function() {
    Route::get('/', function () {
        return view('guest.welcome');
    })->name('welcome');
    Route::get('/locale', 'Guest\HomeController@setLocale')->name('setlocale');
    Route::get('/precheckin/{reference}', 'Guest\HomeController@precheckin')->name('precheckin');
    Route::post('/precheckin/{reference}', 'Guest\HomeController@precheckin')->name('precheckin');
    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Guest\Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Guest\Auth\LoginController@login');
        Route::post('logout', 'Guest\Auth\LoginController@logout')->name('logout');
        Route::get('logout', 'Guest\Auth\LoginController@logout')->name('logout');

        // Registration Routes...
        /*if ($options['register'] ?? true) {
            Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
            Route::post('register', 'Auth\RegisterController@register');
        }*/
    });

    Route::group(['middleware' => 'auth:bookinguest'], function () {
        Route::get('/account', 'Guest\AccountController@index')->name("home");
        Route::post('/update', 'Guest\AccountController@updateCheckin')->name("updatecheckin");
        Route::get('/account/identity', 'Guest\AccountController@identificationFile')->name("ident");
        Route::get('/sendkeycode', 'Guest\AccountController@sendKeycode')->name("sendkeycode");
        Route::get('/sendcheckout', 'Guest\AccountController@sendCheckout')->name("sendcheckout");
    });

});

Route::group(["domain" => config("app.owners_sub").".".config("app.root")], function() {
    Route::get('/', function () {
        if(auth()->user()){
            return redirect()->route('home');
        }
        return view('welcome');
    });
    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);
    Route::get('/timeouttest', 'HomeController@timeouttest')->name('timeouttest');
    Route::get('/invitation', 'HomeController@invitation')->name('invitation');
    Route::post('/invitation', 'HomeController@invitation')->name('invitation');

    Route::post('/api/bsSync', 'HomeController@bsSync')->name('api.bsSync');
    Route::post('/api/keynest', 'HomeController@keynestWebhook')->name('api.keynest');

    Route::get('/deposit/{id}', 'DepositController@deposit')->name("deposit");
    Route::post('/deposit/{id}', 'DepositController@deposit')->name("deposit");
    Route::get('/deposit/{id}/confirm', 'DepositController@depositConfirm')->name("depositConfirm");
    Route::post('/deposit/{id}/confirm', 'DepositController@depositConfirm')->name("depositConfirm");

    Route::group(['prefix' => 'auth'], function () {
        Auth::routes(['register' => false]);
    });

    Route::get('/jhCgv', 'HomeController@jhCgv')->name("jhCgv");

    Route::group(['middleware' => ['cgv','auth']], function(){
        Route::get('/', 'AccountController@cgv')->name("cgv");
        Route::post('/', 'AccountController@cgv')->name("cgv");
        Route::get('/account', 'AccountController@index')->name("home");
        Route::get('/properties', 'AccountController@properties')->name("properties");
        Route::get('/calendars', 'AccountController@calendars')->name("calendars");
        Route::post('/book/{id}', 'AccountController@book')->name("book");
        Route::post('/stats', 'AccountController@stats')->name("stats");
        Route::get('/property/create', 'AccountController@createProperty')->name("createProperty");
        Route::post('/property/create', 'AccountController@createProperty')->name("createProperty");

        Route::get('/property/{propertyId}', 'AccountController@property')->name("property");
        Route::post('/property/{propertyId}', 'AccountController@property')->name("property");


        Route::get('/property/{propertyId}/documents', 'AccountController@documents')->name("documents");
        Route::get('/property/{propertyId}/reports', 'AccountController@reports')->name("reports");
        Route::get('/property/{propertyId}/report/{reportId}', 'AccountController@report')->name("report");
        Route::get('/property/{propertyId}/invoice/{reportId}', 'AccountController@invoice')->name("invoice");

        //Route::get('/contract/{propertyId}', 'AccountController@createContract')->name("genContract");
        //Route::get('/signedContract/{propertyId}', 'AccountController@signedContract')->name("getContract");
        Route::get('/attestloc/{propertyId}', 'AccountController@attestloc')->name("attestlocfile");
        Route::get('/ranking/{propertyId}', 'AccountController@ranking')->name("rankingfile");
        Route::get('/inventory/{propertyId}', 'AccountController@inventory')->name("inventoryfile");
        Route::get('/annexe/{propertyId}', 'AccountController@annexe')->name("annexefile");
        Route::get('/assessment/{propertyId}', 'AccountController@assessment')->name("assessmentfile");
        Route::get('/keys/{propertyId}', 'AccountController@keys')->name("keysfile");

        //Route::post('/uploadContract/{propertyId}', 'AccountController@uploadContract')->name("uploadContract");
        Route::post('/uploadRanking/{propertyId}', 'AccountController@uploadRanking')->name("uploadRanking");
        Route::post('/uploadAttest/{propertyId}', 'AccountController@uploadAttestLoc')->name("uploadAttest");

    });
});

Route::get('/syncrentals/{id?}', 'HomeController@syncRentals');
Route::get('/testsync', 'HomeController@testsyncrentals');
Route::get('/getbookings', 'HomeController@getBookings');

app/Http/Controllers/Guest/AccountController.php
<?php

namespace App\Http\Controllers\Guest;

use App\BookingGuest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Exception;
use Illuminate\Support\MessageBag;
use Mail;
use ZipArchive;
use DOMDocument;
use App\Helpers\Mailer;
use App\User;
use App\Amenity;
use App\Property;
use App\PropertyAmenity;
use App\PropertyDetails;
use App\Report;
use Carbon\Carbon;
use PhpOffice\PhpWord\TemplateProcessor;
use App\Admin\Extensions\Form\Field\Checkbox;
use Khill\Lavacharts\Lavacharts;
use App\BookingSync\BookingSync;
use Dompdf\Dompdf;

class AccountController extends Controller
{
    protected $bookingSync;
    
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        /** @var $user BookingGuest */
        $user = auth()->user();
        $booking = $user->booking;
        return view('guest.account.home', [
            'user' => $user,
            'booking' => $booking,
        ]);
    }


    public function identificationFile(){
        $user = auth()->user();
        if(file_exists($user->ident_file)) {
            $extension = explode('.', $user->ident_file);
            $extension = $extension[count($extension)-1];
            attachFile($user->ident_file, $user->firstname . '-' . $user->lastname . '.' . $extension);
        }
    }

    public function updateCheckin(Request $request){
        $user = auth()->user();
        if($request->validate(['arrival' => 'required','checkin' => 'required'])){
            $user->fill([
                'arrival' => Carbon::createFromFormat('d/m/Y H:i', $request->arrival),
                'checkin' => Carbon::createFromFormat('d/m/Y H:i', $request->checkin),
                'checkout' => Carbon::createFromFormat('d/m/Y H:i', $request->checkout),
            ]);
            try {
                $user->save();
            } catch (\Exception $e) {
                throw new \Exception($e);
            }
            
        }
        return redirect(route('guest.home'));
    }

    public function sendKeycode(){
        $user = auth()->user();
        if($user->booking->deposit && !$user->booking->deposit->paid) {
            return redirect(route('guest.home'))->withErrorUser(new MessageBag(['title' => __('Vous devez payer votre caution avant de pouvoir accéder à ces informations !')]));
        }else if($user->booking->property->keynest_auto){
            Mailer::sendGuestKeyCode($user);
        }
        return redirect(route('guest.home'))->withSuccessUser(new MessageBag(['title' =>'Mail envoyé']));
    }

    public function sendCheckout(){
        $user = auth()->user();
        if($user->booking->deposit && !$user->booking->deposit->paid){
            return redirect(route('guest.home'))->withErrorUser(new MessageBag(['title' => __('Vous devez payer votre caution avant de pouvoir accéder à ces informations !')]));
        }else if($user->booking->property->keynest_auto_checkout){
            Mailer::sendGuestAutoCheckout($user);
        }
        return redirect(route('guest.home'))->withSuccessUser(new MessageBag(['title' =>'Mail envoyé']));
    }

}

app/Http/Controllers/Guest/HomeController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Booking;
use App\BookingGuest;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Exception;
use Illuminate\Support\Arr;
use Illuminate\Support\MessageBag;
use Log;
use App\Helpers\Mailer;

class HomeController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    public function setLocale(Request $request){
        $langs = config('app.all_langs');
        $lang = $request->get('lang');
        if(in_array($lang, $langs)){
            session()->put('lang', $lang);
        }
        return redirect()->back();
    }
    
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function precheckin(Request $request, $reference)
    {
        $booking = Booking::where("reference", "=", $reference)->first();

        if($booking && !$booking->bookingguest)
        {
            $guest = json_decode($booking->guest);
            if($request->method() == "POST")
            {
                $rules = [
                    'firstname' => 'required',
                    'lastname' => 'required',
                    'email' => 'required|email',
                    'phone' => 'required',
                    'transport_type' => 'required',
                    'ident_type' => 'required',
                    'ident_number' => 'required',
                    'ident_file' => 'required',
                    'ident_expiration' => 'required',
                    'country_id' => 'required',
                    'arrival' => 'required',
                    'checkin' => 'required',
                    'checkout' => 'required',
                    'g-recaptcha-response' => 'required|recaptcha',
                ];
                if($booking->source !== "Airbnb"){
                    $rules = array_merge($rules, [
                        'card_type' => 'required',
                        'card_holder' => 'required',
                        'card_last_digits' => 'required',
                        'card_expiration' => 'required'
                    ]);
                }
                $request->validate($rules);
                $data = $request->all();
                $data["booking_id"] = $booking->id;

                //var_dump($request->file('contract'));die;
                $file = $request->file('ident_file');
                $path = $booking->getFileFolder();
                $filename = $booking->getIdentFileName($file->extension());
                $file->move($path, $filename);
                $file = $booking->getUploadFolder() . '/' . $filename;
                $data['ident_file'] = $file;
                $data['arrival'] = Carbon::createFromFormat('d/m/Y H:i', $data['arrival']);
                $data['checkin'] = Carbon::createFromFormat('d/m/Y H:i', $data['checkin']);
                $data['checkout'] = Carbon::createFromFormat('d/m/Y H:i', $data['checkout']);
                $data['ident_expiration'] = Carbon::createFromFormat('d/m/Y', $data['ident_expiration']);
                $user = BookingGuest::create($data);
                try
                {
                    if($user->id)
                    {
                        Mailer::sendGuestAccess($user);
                        return redirect(route('guest.login'))->withSuccessUser(new MessageBag(['title' =>'Registration successful, check your emails.']));
                    }
                } catch(Exception $e)
                {
                    return $e;
                }
            }

            return view('guest.precheckin', [
                "booking" => $booking,
                "guest" => $guest,
                "identTypes" => BookingGuest::getIdentTypes(),
                "transportTypes" => BookingGuest::getTransportTypes(),
                "cardTypes" => BookingGuest::getCardTypes(),
            ]);
        }
        return redirect(route('guest.welcome'));
    }

    public function index()
    {
        /*  @var $icalevents ICalEvents */
        $content = "";
        $user = auth('bookinguest')->user();
        return view('home', ["content" => $content, "user" => $user]);
    }
}

resources/views/guest/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Jeffrey Host') }}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/account') }}">
                        JeffreyHost<br/>
                        <span>{{ __("Espace voyageurs") }}"</span>
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @if(Auth::user() && isset($user))

                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        <li id="language">
                            <label>{{  __("Langue") }}</label>
                            <select id="languageselect" name="lang">
                                @foreach(config('app.all_langs') as $l)
                                    <option value="{{$l}}"  {{$l == app()->getLocale() ? 'selected' : ''}}>{{$l}}</option>
                                @endforeach
                            </select>
                        </li>
                        @guest
                            <li><a href="{{ route('guest.login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->firstname }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('guest.logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Déconnexion
                                        </a>

                                        <form id="logout-form" action="{{ route('guest.logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @include('partials.alerts')

        @yield('content')
    </div>
    @include('guest.layouts.footer')
    <!-- Scripts -->
    @yield('scripts')
    
</body>
</html>

resources/views/guest/layouts/footer.blade.php
<footer>
    Jeffrey Host Limited © {{ getYear() }}
</footer>
@section("scripts")
<script src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script>
moment.locale('fr', {
    months: 'janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre'.split('_'),
    monthsShort: 'janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.'.split('_'),
    monthsParseExact: true,
    weekdays: 'dimanche_lundi_mardi_mercredi_jeudi_vendredi_samedi'.split('_'),
    weekdaysShort: 'dim._lun._mar._mer._jeu._ven._sam.'.split('_'),
    weekdaysMin: 'Di_Lu_Ma_Me_Je_Ve_Sa'.split('_'),
    weekdaysParseExact: true,
    longDateFormat: {
        LT: 'HH:mm',
        LTS: 'HH:mm:ss',
        L: 'DD/MM/YYYY',
        LL: 'D MMMM YYYY',
        LLL: 'D MMMM YYYY HH:mm',
        LLLL: 'dddd D MMMM YYYY HH:mm'
    },
    calendar: {
        sameDay: '[Aujourd’hui à] LT',
        nextDay: '[Demain à] LT',
        nextWeek: 'dddd [à] LT',
        lastDay: '[Hier à] LT',
        lastWeek: 'dddd [dernier à] LT',
        sameElse: 'L'
    },
    relativeTime: {
        future: 'dans %s',
        past: 'il y a %s',
        s: 'quelques secondes',
        m: 'une minute',
        mm: '%d minutes',
        h: 'une heure',
        hh: '%d heures',
        d: 'un jour',
        dd: '%d jours',
        M: 'un mois',
        MM: '%d mois',
        y: 'un an',
        yy: '%d ans'
    },
    dayOfMonthOrdinalParse: /\d{1,2}(er|e)/,
    ordinal: function (number) {
        return number + (number === 1 ? 'er' : 'e');
    },
    meridiemParse: /PD|MD/,
    isPM: function (input) {
        return input.charAt(0) === 'M';
    },
    // In case the meridiem units are not separated around 12, then implement
    // this function (look at locale/id.js for an example).
    // meridiemHour : function (hour, meridiem) {
    //     return /* 0-23 hour, given meridiem token and hour 1-12 */ ;
    // },
    meridiem: function (hours, minutes, isLower) {
        return hours < 12 ? 'PD' : 'MD';
    },
    week: {
        dow: 1, // Monday is the first day of the week.
        doy: 4  // Used to determine first week of the year.
    }
});

$(function(){
    let langRoute = "{{ route('guest.setlocale') }}";
    $('#languageselect').on('change', function(e){
        console.log(e.target.value);
        window.location.href = langRoute + '?lang=' + e.target.value;
    });
});
</script>